### ISSUE TITLE
스터디룸 / 마감직전 과제 progress bar 추가

### ISSUE THREAD

**Issue by chaehyun-oh** [team-swith/swith-client#28]
### 📌 설명

- 스터디룸 / 마감직전 과제 progress bar 추가 (라이브러리 사용)

### 📝 작업 내용

- [x] 스터디룸 / 마감직전 과제 progress bar 추가 (라이브러리 사용 - react-circular-progressbar)

**Comment by wontory** [comment]
Next UI랑 shadcn/ui랑 포지션이 겹쳐서 구성하기 힘드실 수도 있을 것 같은데 괜찮으실까요?
